// Code generated by protoc-gen-go.
// source: loadguide.proto
// DO NOT EDIT!

/*
Package loadguide is a generated protocol buffer package.

It is generated from these files:
	loadguide.proto

It has these top-level messages:
	PowerRequest
	LoadReply
	WhoAmI
	LoadResMsg
	Signal
	Empty
*/
package loadguide

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PowerRequest struct {
	Core   int32 `protobuf:"varint,1,opt,name=core" json:"core,omitempty"`
	Weight int32 `protobuf:"varint,2,opt,name=weight" json:"weight,omitempty"`
}

func (m *PowerRequest) Reset()                    { *m = PowerRequest{} }
func (m *PowerRequest) String() string            { return proto.CompactTextString(m) }
func (*PowerRequest) ProtoMessage()               {}
func (*PowerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PowerRequest) GetCore() int32 {
	if m != nil {
		return m.Core
	}
	return 0
}

func (m *PowerRequest) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type LoadReply struct {
	Urls      []string `protobuf:"bytes,1,rep,name=urls" json:"urls,omitempty"`
	Requests  int32    `protobuf:"varint,2,opt,name=requests" json:"requests,omitempty"`
	Workers   int32    `protobuf:"varint,3,opt,name=workers" json:"workers,omitempty"`
	Timeout   int32    `protobuf:"varint,4,opt,name=timeout" json:"timeout,omitempty"`
	Useragent string   `protobuf:"bytes,5,opt,name=useragent" json:"useragent,omitempty"`
	Trace     bool     `protobuf:"varint,6,opt,name=trace" json:"trace,omitempty"`
}

func (m *LoadReply) Reset()                    { *m = LoadReply{} }
func (m *LoadReply) String() string            { return proto.CompactTextString(m) }
func (*LoadReply) ProtoMessage()               {}
func (*LoadReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoadReply) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *LoadReply) GetRequests() int32 {
	if m != nil {
		return m.Requests
	}
	return 0
}

func (m *LoadReply) GetWorkers() int32 {
	if m != nil {
		return m.Workers
	}
	return 0
}

func (m *LoadReply) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *LoadReply) GetUseragent() string {
	if m != nil {
		return m.Useragent
	}
	return ""
}

func (m *LoadReply) GetTrace() bool {
	if m != nil {
		return m.Trace
	}
	return false
}

type WhoAmI struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Laddr string `protobuf:"bytes,2,opt,name=laddr" json:"laddr,omitempty"`
	Raddr string `protobuf:"bytes,3,opt,name=raddr" json:"raddr,omitempty"`
}

func (m *WhoAmI) Reset()                    { *m = WhoAmI{} }
func (m *WhoAmI) String() string            { return proto.CompactTextString(m) }
func (*WhoAmI) ProtoMessage()               {}
func (*WhoAmI) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *WhoAmI) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WhoAmI) GetLaddr() string {
	if m != nil {
		return m.Laddr
	}
	return ""
}

func (m *WhoAmI) GetRaddr() string {
	if m != nil {
		return m.Raddr
	}
	return ""
}

type LoadResMsg struct {
	ID        string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Url       string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Status    int32  `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	Timestamp int32  `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *LoadResMsg) Reset()                    { *m = LoadResMsg{} }
func (m *LoadResMsg) String() string            { return proto.CompactTextString(m) }
func (*LoadResMsg) ProtoMessage()               {}
func (*LoadResMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoadResMsg) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *LoadResMsg) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *LoadResMsg) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *LoadResMsg) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Signal struct {
	Number int32 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
}

func (m *Signal) Reset()                    { *m = Signal{} }
func (m *Signal) String() string            { return proto.CompactTextString(m) }
func (*Signal) ProtoMessage()               {}
func (*Signal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Signal) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*PowerRequest)(nil), "loadguide.PowerRequest")
	proto.RegisterType((*LoadReply)(nil), "loadguide.LoadReply")
	proto.RegisterType((*WhoAmI)(nil), "loadguide.WhoAmI")
	proto.RegisterType((*LoadResMsg)(nil), "loadguide.LoadResMsg")
	proto.RegisterType((*Signal)(nil), "loadguide.Signal")
	proto.RegisterType((*Empty)(nil), "loadguide.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LoadGuide service

type LoadGuideClient interface {
	SendLoad(ctx context.Context, in *PowerRequest, opts ...grpc.CallOption) (*LoadReply, error)
	Ping(ctx context.Context, in *WhoAmI, opts ...grpc.CallOption) (*WhoAmI, error)
	SendResult(ctx context.Context, opts ...grpc.CallOption) (LoadGuide_SendResultClient, error)
	SendSignal(ctx context.Context, in *Signal, opts ...grpc.CallOption) (*Empty, error)
}

type loadGuideClient struct {
	cc *grpc.ClientConn
}

func NewLoadGuideClient(cc *grpc.ClientConn) LoadGuideClient {
	return &loadGuideClient{cc}
}

func (c *loadGuideClient) SendLoad(ctx context.Context, in *PowerRequest, opts ...grpc.CallOption) (*LoadReply, error) {
	out := new(LoadReply)
	err := grpc.Invoke(ctx, "/loadguide.LoadGuide/SendLoad", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadGuideClient) Ping(ctx context.Context, in *WhoAmI, opts ...grpc.CallOption) (*WhoAmI, error) {
	out := new(WhoAmI)
	err := grpc.Invoke(ctx, "/loadguide.LoadGuide/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadGuideClient) SendResult(ctx context.Context, opts ...grpc.CallOption) (LoadGuide_SendResultClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_LoadGuide_serviceDesc.Streams[0], c.cc, "/loadguide.LoadGuide/SendResult", opts...)
	if err != nil {
		return nil, err
	}
	x := &loadGuideSendResultClient{stream}
	return x, nil
}

type LoadGuide_SendResultClient interface {
	Send(*LoadResMsg) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type loadGuideSendResultClient struct {
	grpc.ClientStream
}

func (x *loadGuideSendResultClient) Send(m *LoadResMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *loadGuideSendResultClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loadGuideClient) SendSignal(ctx context.Context, in *Signal, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/loadguide.LoadGuide/SendSignal", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LoadGuide service

type LoadGuideServer interface {
	SendLoad(context.Context, *PowerRequest) (*LoadReply, error)
	Ping(context.Context, *WhoAmI) (*WhoAmI, error)
	SendResult(LoadGuide_SendResultServer) error
	SendSignal(context.Context, *Signal) (*Empty, error)
}

func RegisterLoadGuideServer(s *grpc.Server, srv LoadGuideServer) {
	s.RegisterService(&_LoadGuide_serviceDesc, srv)
}

func _LoadGuide_SendLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadGuideServer).SendLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loadguide.LoadGuide/SendLoad",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadGuideServer).SendLoad(ctx, req.(*PowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadGuide_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmI)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadGuideServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loadguide.LoadGuide/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadGuideServer).Ping(ctx, req.(*WhoAmI))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadGuide_SendResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LoadGuideServer).SendResult(&loadGuideSendResultServer{stream})
}

type LoadGuide_SendResultServer interface {
	SendAndClose(*Empty) error
	Recv() (*LoadResMsg, error)
	grpc.ServerStream
}

type loadGuideSendResultServer struct {
	grpc.ServerStream
}

func (x *loadGuideSendResultServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *loadGuideSendResultServer) Recv() (*LoadResMsg, error) {
	m := new(LoadResMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _LoadGuide_SendSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Signal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadGuideServer).SendSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loadguide.LoadGuide/SendSignal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadGuideServer).SendSignal(ctx, req.(*Signal))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoadGuide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "loadguide.LoadGuide",
	HandlerType: (*LoadGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLoad",
			Handler:    _LoadGuide_SendLoad_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _LoadGuide_Ping_Handler,
		},
		{
			MethodName: "SendSignal",
			Handler:    _LoadGuide_SendSignal_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendResult",
			Handler:       _LoadGuide_SendResult_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "loadguide.proto",
}

func init() { proto.RegisterFile("loadguide.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x52, 0xcb, 0x6a, 0xdc, 0x40,
	0x10, 0xdc, 0xd9, 0x87, 0xbc, 0x6a, 0x82, 0x63, 0x37, 0x4e, 0x32, 0x2c, 0x39, 0x88, 0x81, 0x80,
	0x4e, 0x7b, 0x88, 0x4f, 0x49, 0x4e, 0x31, 0x0e, 0x89, 0x21, 0x81, 0x65, 0x7c, 0xc8, 0x79, 0xbc,
	0x1a, 0x64, 0x11, 0x49, 0xa3, 0xcc, 0x83, 0xc5, 0xdf, 0x93, 0x9f, 0xcb, 0x67, 0x84, 0x79, 0x78,
	0x25, 0xd8, 0xdc, 0xba, 0xaa, 0xa8, 0xd6, 0x54, 0x97, 0xe0, 0x65, 0xab, 0x44, 0x55, 0xbb, 0xa6,
	0x92, 0xdb, 0x41, 0x2b, 0xab, 0x30, 0x3f, 0x12, 0xec, 0x23, 0xbc, 0xd8, 0xa9, 0x83, 0xd4, 0x5c,
	0xfe, 0x76, 0xd2, 0x58, 0x44, 0x58, 0xee, 0x95, 0x96, 0x94, 0x14, 0xa4, 0x5c, 0xf1, 0x30, 0xe3,
	0x6b, 0xc8, 0x0e, 0xb2, 0xa9, 0x1f, 0x2d, 0x9d, 0x07, 0x36, 0x21, 0xf6, 0x87, 0x40, 0xfe, 0x5d,
	0x89, 0x8a, 0xcb, 0xa1, 0x7d, 0xf2, 0x4e, 0xa7, 0x5b, 0x43, 0x49, 0xb1, 0x28, 0x73, 0x1e, 0x66,
	0xdc, 0xc0, 0x5a, 0xc7, 0xc5, 0x26, 0x79, 0x8f, 0x18, 0x29, 0x9c, 0x1d, 0x94, 0xfe, 0x25, 0xb5,
	0xa1, 0x8b, 0x20, 0x3d, 0x43, 0xaf, 0xd8, 0xa6, 0x93, 0xca, 0x59, 0xba, 0x8c, 0x4a, 0x82, 0xf8,
	0x16, 0x72, 0x67, 0xa4, 0x16, 0xb5, 0xec, 0x2d, 0x5d, 0x15, 0xa4, 0xcc, 0xf9, 0x48, 0xe0, 0x15,
	0xac, 0xac, 0x16, 0x7b, 0x49, 0xb3, 0x82, 0x94, 0x6b, 0x1e, 0x01, 0xfb, 0x06, 0xd9, 0xcf, 0x47,
	0xf5, 0xb9, 0xbb, 0xf3, 0x2f, 0xec, 0x45, 0x17, 0xb3, 0xe5, 0x3c, 0xcc, 0xde, 0xd3, 0x8a, 0xaa,
	0xd2, 0xe1, 0x79, 0x39, 0x8f, 0xc0, 0xb3, 0x3a, 0xb0, 0x8b, 0xc8, 0x06, 0xc0, 0x2a, 0x80, 0x18,
	0xd7, 0xfc, 0x30, 0x35, 0x9e, 0xc3, 0xfc, 0xee, 0x36, 0xed, 0x9a, 0x37, 0xb7, 0x78, 0x01, 0x0b,
	0xa7, 0xdb, 0xb4, 0xc7, 0x8f, 0xfe, 0x6e, 0xc6, 0x0a, 0xeb, 0x9e, 0x03, 0x26, 0xe4, 0x53, 0xf8,
	0x40, 0xc6, 0x8a, 0x6e, 0x48, 0x09, 0x47, 0x82, 0x15, 0x90, 0xdd, 0x37, 0x75, 0x2f, 0x82, 0xbf,
	0x77, 0xdd, 0x83, 0xd4, 0xa9, 0x8d, 0x84, 0xd8, 0x19, 0xac, 0xbe, 0x74, 0x83, 0x7d, 0x7a, 0xff,
	0x37, 0x15, 0xf0, 0xd5, 0x57, 0x89, 0x9f, 0x60, 0x7d, 0x2f, 0xfb, 0xca, 0x13, 0xf8, 0x66, 0x3b,
	0x76, 0x3e, 0xed, 0x77, 0x73, 0x35, 0x11, 0x8e, 0xdd, 0xb1, 0x19, 0x6e, 0x61, 0xb9, 0x6b, 0xfa,
	0x1a, 0x2f, 0x27, 0x7a, 0x3c, 0xdb, 0xe6, 0x94, 0x62, 0x33, 0xfc, 0x00, 0xe0, 0x3f, 0xc6, 0xa5,
	0x71, 0xad, 0xc5, 0x57, 0x27, 0x5b, 0xfd, 0x89, 0x36, 0x17, 0x13, 0x3a, 0xbc, 0x98, 0xcd, 0x4a,
	0x82, 0xd7, 0xd1, 0x9a, 0x42, 0x4e, 0xb7, 0x47, 0xea, 0x7f, 0xb6, 0x9b, 0x77, 0x70, 0xd9, 0xa8,
	0x6d, 0xad, 0x87, 0xfd, 0x28, 0xde, 0x9c, 0x1f, 0xc3, 0xef, 0xfc, 0x7f, 0xbd, 0x23, 0x0f, 0x59,
	0xf8, 0xc1, 0xaf, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xc9, 0xb5, 0xdc, 0xf3, 0x02, 0x00,
	0x00,
}
