// Code generated by protoc-gen-go.
// source: loadguide.proto
// DO NOT EDIT!

/*
Package loadguide is a generated protocol buffer package.

It is generated from these files:
	loadguide.proto

It has these top-level messages:
	PowerRequest
	LoadReply
	WhoAmI
	LoadResMsg
	Empty
*/
package loadguide

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PowerRequest struct {
	Core   int32 `protobuf:"varint,1,opt,name=core" json:"core,omitempty"`
	Weight int32 `protobuf:"varint,2,opt,name=weight" json:"weight,omitempty"`
}

func (m *PowerRequest) Reset()                    { *m = PowerRequest{} }
func (m *PowerRequest) String() string            { return proto.CompactTextString(m) }
func (*PowerRequest) ProtoMessage()               {}
func (*PowerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PowerRequest) GetCore() int32 {
	if m != nil {
		return m.Core
	}
	return 0
}

func (m *PowerRequest) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type LoadReply struct {
	Urls     []string `protobuf:"bytes,1,rep,name=urls" json:"urls,omitempty"`
	Requests int32    `protobuf:"varint,2,opt,name=requests" json:"requests,omitempty"`
	Workers  int32    `protobuf:"varint,3,opt,name=workers" json:"workers,omitempty"`
}

func (m *LoadReply) Reset()                    { *m = LoadReply{} }
func (m *LoadReply) String() string            { return proto.CompactTextString(m) }
func (*LoadReply) ProtoMessage()               {}
func (*LoadReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoadReply) GetUrls() []string {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *LoadReply) GetRequests() int32 {
	if m != nil {
		return m.Requests
	}
	return 0
}

func (m *LoadReply) GetWorkers() int32 {
	if m != nil {
		return m.Workers
	}
	return 0
}

type WhoAmI struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Addr string `protobuf:"bytes,3,opt,name=addr" json:"addr,omitempty"`
}

func (m *WhoAmI) Reset()                    { *m = WhoAmI{} }
func (m *WhoAmI) String() string            { return proto.CompactTextString(m) }
func (*WhoAmI) ProtoMessage()               {}
func (*WhoAmI) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *WhoAmI) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WhoAmI) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *WhoAmI) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type LoadResMsg struct {
	ID        string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Url       string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Status    int32  `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	Timestamp int32  `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *LoadResMsg) Reset()                    { *m = LoadResMsg{} }
func (m *LoadResMsg) String() string            { return proto.CompactTextString(m) }
func (*LoadResMsg) ProtoMessage()               {}
func (*LoadResMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoadResMsg) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *LoadResMsg) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *LoadResMsg) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *LoadResMsg) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*PowerRequest)(nil), "loadguide.PowerRequest")
	proto.RegisterType((*LoadReply)(nil), "loadguide.LoadReply")
	proto.RegisterType((*WhoAmI)(nil), "loadguide.WhoAmI")
	proto.RegisterType((*LoadResMsg)(nil), "loadguide.LoadResMsg")
	proto.RegisterType((*Empty)(nil), "loadguide.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LoadGuide service

type LoadGuideClient interface {
	SendLoad(ctx context.Context, in *PowerRequest, opts ...grpc.CallOption) (*LoadReply, error)
	Ping(ctx context.Context, in *WhoAmI, opts ...grpc.CallOption) (*WhoAmI, error)
	SendResult(ctx context.Context, in *LoadResMsg, opts ...grpc.CallOption) (*Empty, error)
}

type loadGuideClient struct {
	cc *grpc.ClientConn
}

func NewLoadGuideClient(cc *grpc.ClientConn) LoadGuideClient {
	return &loadGuideClient{cc}
}

func (c *loadGuideClient) SendLoad(ctx context.Context, in *PowerRequest, opts ...grpc.CallOption) (*LoadReply, error) {
	out := new(LoadReply)
	err := grpc.Invoke(ctx, "/loadguide.LoadGuide/SendLoad", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadGuideClient) Ping(ctx context.Context, in *WhoAmI, opts ...grpc.CallOption) (*WhoAmI, error) {
	out := new(WhoAmI)
	err := grpc.Invoke(ctx, "/loadguide.LoadGuide/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loadGuideClient) SendResult(ctx context.Context, in *LoadResMsg, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/loadguide.LoadGuide/SendResult", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LoadGuide service

type LoadGuideServer interface {
	SendLoad(context.Context, *PowerRequest) (*LoadReply, error)
	Ping(context.Context, *WhoAmI) (*WhoAmI, error)
	SendResult(context.Context, *LoadResMsg) (*Empty, error)
}

func RegisterLoadGuideServer(s *grpc.Server, srv LoadGuideServer) {
	s.RegisterService(&_LoadGuide_serviceDesc, srv)
}

func _LoadGuide_SendLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadGuideServer).SendLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loadguide.LoadGuide/SendLoad",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadGuideServer).SendLoad(ctx, req.(*PowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadGuide_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmI)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadGuideServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loadguide.LoadGuide/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadGuideServer).Ping(ctx, req.(*WhoAmI))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoadGuide_SendResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadResMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadGuideServer).SendResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loadguide.LoadGuide/SendResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadGuideServer).SendResult(ctx, req.(*LoadResMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _LoadGuide_serviceDesc = grpc.ServiceDesc{
	ServiceName: "loadguide.LoadGuide",
	HandlerType: (*LoadGuideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendLoad",
			Handler:    _LoadGuide_SendLoad_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _LoadGuide_Ping_Handler,
		},
		{
			MethodName: "SendResult",
			Handler:    _LoadGuide_SendResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loadguide.proto",
}

func init() { proto.RegisterFile("loadguide.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x92, 0x4f, 0x6b, 0xe3, 0x30,
	0x10, 0xc5, 0xe3, 0xfc, 0xd7, 0xb0, 0x64, 0x93, 0x61, 0xb7, 0x35, 0xa6, 0x87, 0x20, 0x28, 0xe4,
	0xe4, 0x43, 0x7b, 0x28, 0xb4, 0xa7, 0x86, 0x94, 0x12, 0x68, 0xc1, 0xa8, 0x94, 0x9e, 0xdd, 0x48,
	0x38, 0xa6, 0x76, 0xe4, 0x4a, 0x32, 0x21, 0x1f, 0xab, 0xdf, 0xb0, 0x48, 0x76, 0x1c, 0x43, 0x6e,
	0x6f, 0x7e, 0x0f, 0x3d, 0x8d, 0x1e, 0x82, 0xbf, 0x99, 0x8c, 0x79, 0x52, 0xa6, 0x5c, 0x84, 0x85,
	0x92, 0x46, 0x22, 0x69, 0x00, 0xbd, 0x87, 0x3f, 0x91, 0xdc, 0x0b, 0xc5, 0xc4, 0x77, 0x29, 0xb4,
	0x41, 0x84, 0xfe, 0x46, 0x2a, 0xe1, 0x7b, 0x73, 0x6f, 0x31, 0x60, 0x4e, 0xe3, 0x05, 0x0c, 0xf7,
	0x22, 0x4d, 0xb6, 0xc6, 0xef, 0x3a, 0x5a, 0x4f, 0xf4, 0x1d, 0xc8, 0x8b, 0x8c, 0x39, 0x13, 0x45,
	0x76, 0xb0, 0x07, 0x4b, 0x95, 0x69, 0xdf, 0x9b, 0xf7, 0x16, 0x84, 0x39, 0x8d, 0x01, 0x8c, 0x55,
	0x95, 0xab, 0xeb, 0xa3, 0xcd, 0x8c, 0x3e, 0x8c, 0xf6, 0x52, 0x7d, 0x09, 0xa5, 0xfd, 0x9e, 0xb3,
	0x8e, 0x23, 0x5d, 0xc1, 0xf0, 0x63, 0x2b, 0x1f, 0xf3, 0xb5, 0xcd, 0xdc, 0xc5, 0x79, 0xb5, 0x0c,
	0x61, 0x4e, 0x5b, 0x66, 0x0e, 0x85, 0x70, 0x79, 0x84, 0x39, 0x6d, 0x59, 0xcc, 0xb9, 0x72, 0x41,
	0x84, 0x39, 0x4d, 0x39, 0x40, 0xb5, 0x9c, 0x7e, 0xd5, 0x09, 0x4e, 0xa0, 0xbb, 0x5e, 0xd5, 0x39,
	0xdd, 0x74, 0x85, 0x53, 0xe8, 0x95, 0x2a, 0xab, 0x43, 0xac, 0xb4, 0x8f, 0xd4, 0x26, 0x36, 0xe5,
	0x71, 0x9d, 0x7a, 0xc2, 0x2b, 0x20, 0x26, 0xcd, 0x85, 0x36, 0x71, 0x5e, 0xf8, 0x7d, 0x67, 0x9d,
	0x00, 0x1d, 0xc1, 0xe0, 0x29, 0x2f, 0xcc, 0xe1, 0xe6, 0xc7, 0xab, 0xca, 0x78, 0xb6, 0xad, 0xe2,
	0x03, 0x8c, 0xdf, 0xc4, 0x8e, 0x5b, 0x80, 0x97, 0xe1, 0xa9, 0xfe, 0x76, 0xd5, 0xc1, 0xbf, 0x96,
	0xd1, 0xf4, 0x48, 0x3b, 0x18, 0x42, 0x3f, 0x4a, 0x77, 0x09, 0xce, 0x5a, 0x7e, 0x55, 0x48, 0x70,
	0x8e, 0x68, 0x07, 0xef, 0x00, 0xec, 0x65, 0x4c, 0xe8, 0x32, 0x33, 0xf8, 0xff, 0x2c, 0xd5, 0x16,
	0x10, 0x4c, 0x5b, 0xd8, 0x6d, 0x4c, 0x3b, 0xcb, 0x6b, 0x98, 0xa5, 0x32, 0x4c, 0x54, 0xb1, 0x39,
	0x99, 0xcb, 0x49, 0xf3, 0x8a, 0xc8, 0xfe, 0x95, 0xc8, 0xfb, 0x1c, 0xba, 0x4f, 0x73, 0xfb, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xe5, 0xa4, 0xde, 0xaf, 0x47, 0x02, 0x00, 0x00,
}
